name: auto magazine publish 

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: check code
        uses: actions/checkout@v4
      
      - name: set python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: install dependency
        run: |
          python -m pip install --upgrade pip
          pip3 install openai
          pip3 install requests

      
      - name: run auto/main.py
        run: python auto/main.py
